/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.dictionaryofficial.view;

import com.mycompany.dictionaryofficial.models.Word;
import javax.swing.JFrame;
import javax.swing.event.DocumentListener;
import javax.swing.event.DocumentEvent;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * create read update delete view.
 * 
 * @author Chinh
 */

public class CrudView extends JFrame implements ActionListener {

    /**
     *
     */
    private static final long serialVersionUID = 1L;

    /**
     * Creates new form CrudView
     */
    public CrudView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // @SuppressWarnings("unchecked")
    // <editor-fold default state="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crudPanel = new javax.swing.JPanel();
        crudWord = new javax.swing.JTextField();
        crudPro = new javax.swing.JTextField();
        crudTitle = new javax.swing.JLabel();
        crudMean = new javax.swing.JTextField();
        crudPartOfSpeech = new javax.swing.JTextField();
        scrollPaneCrud = new javax.swing.JScrollPane();
        crudDsc = new javax.swing.JTextPane();
        crudButton = new javax.swing.JButton();
        crudSynonym = new javax.swing.JTextField();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        crudPanel.setBackground(new java.awt.Color(255, 255, 255));

        crudWord.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crudWord.getDocument().addDocumentListener(new  DocumentValidateListener());
        crudWord.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Word  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        crudPro.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        crudPro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pronunciation  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        crudTitle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        crudTitle.setForeground(new java.awt.Color(0, 102, 102));
        crudTitle.setText("Create new word");

        crudMean.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crudMean.getDocument().addDocumentListener(new  DocumentValidateListener());
        crudMean.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Meaning  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        crudPartOfSpeech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crudPartOfSpeech.getDocument().addDocumentListener(new  DocumentValidateListener());
        crudPartOfSpeech.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Type", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 153, 153)), "Part of speech", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        scrollPaneCrud.setBackground(new java.awt.Color(255, 255, 255));
        scrollPaneCrud.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Description and examples    ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 153, 153))); // NOI18N
        scrollPaneCrud.setAutoscrolls(true);

        crudDsc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crudDsc.getDocument().addDocumentListener(new  DocumentValidateListener());
        scrollPaneCrud.setViewportView(crudDsc);

        crudButton.setBackground(new java.awt.Color(255, 255, 255));
        crudButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        crudButton.setText("Update");
        crudButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        crudButton.setEnabled(false);

        crudSynonym.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        crudSynonym.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Synonym  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 153, 153))); // NOI18N

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/dictionaryofficial/images/back .png"))); // NOI18N

        javax.swing.GroupLayout crudPanelLayout = new javax.swing.GroupLayout(crudPanel);
        crudPanel.setLayout(crudPanelLayout);
        crudPanelLayout.setHorizontalGroup(
            crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(crudPanelLayout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(290, 290, 290)
                        .addComponent(crudTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 425, Short.MAX_VALUE))
                    .addGroup(crudPanelLayout.createSequentialGroup()
                        .addGroup(crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crudSynonym)
                            .addComponent(scrollPaneCrud, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(crudPanelLayout.createSequentialGroup()
                                .addGroup(crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(crudMean, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
                                    .addComponent(crudWord))
                                .addGroup(crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(crudPanelLayout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(crudPro))
                                    .addGroup(crudPanelLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(crudPartOfSpeech)))))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, crudPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crudButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        crudPanelLayout.setVerticalGroup(
            crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crudTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back))
                .addGap(33, 33, 33)
                .addGroup(crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crudWord, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crudPro, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(crudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(crudMean)
                    .addComponent(crudPartOfSpeech))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crudSynonym, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPaneCrud, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(crudButton, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crudPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(crudPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void initFormEdit(Word word) {
        this.crudTitle.setText("Edit word");
        this.crudButton.setText("Update");
        this.crudWord.setText(word.getWordTarget());
        this.crudMean.setText(word.getWordExplain());
        this.crudPro.setText(word.getPronunciation());
        this.crudDsc.setText(word.getDescription().replace("\t", "\n"));
        this.crudPartOfSpeech.setText(word.getPartOfSpeech());
        this.crudSynonym.setText(word.getSynonym());
        this.crudWord.requestFocus();
        this.crudButton.setActionCommand("edit");
    }

    public void initFormCreate() {
        this.crudTitle.setText("Create new word");
        this.crudButton.setText("Create");
        this.crudWord.setText("");
        this.crudMean.setText("");
        this.crudPro.setText("");
        this.crudDsc.setText("");
        this.crudPartOfSpeech.setText("");
        this.crudSynonym.setText("");
        this.crudWord.requestFocus();
        this.crudButton.setActionCommand("create");
    }

    public String[] getData() {
        String[] result = new String[6];
        result[0] = crudWord.getText().trim().toLowerCase();
        result[1] = crudMean.getText().trim().toLowerCase();
        result[2] = crudPro.getText().trim().toLowerCase();
        result[3] = crudPartOfSpeech.getText().trim().toLowerCase();
        result[4] = crudDsc.getText().trim().toLowerCase().replace("\n","\t");
        result[5] = crudSynonym.getText().trim().toLowerCase();
        return result;
    }

    public void addBackListener(ActionListener listener) {
        back.addActionListener(listener);
    }

    public void addCrudBtnListener(ActionListener listener) {
        crudButton.addActionListener(listener);
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton crudButton;
    private javax.swing.JTextPane crudDsc;
    private javax.swing.JTextField crudMean;
    private javax.swing.JPanel crudPanel;
    private javax.swing.JTextField crudPartOfSpeech;
    private javax.swing.JTextField crudPro;
    private javax.swing.JTextField crudSynonym;
    private javax.swing.JLabel crudTitle;
    private javax.swing.JTextField crudWord;
    private javax.swing.JScrollPane scrollPaneCrud;
    // End of variables declaration//GEN-END:variables

    public void actionPerformed(ActionEvent e) {
        // TO DO Auto-generated method stub

    }

	class DocumentValidateListener implements DocumentListener {
		public void changedUpdate(DocumentEvent e) {
				changed();
		}
		public void removeUpdate(DocumentEvent e) {
				changed();
		}
		public void insertUpdate(DocumentEvent e) {
				changed();
		}

		public void changed() {
			if (crudWordValidate() && crudMeanValidate() && crudDscValidate()){
				crudButton.setEnabled(true);
				return;
			}
			crudButton.setEnabled(false);
		}
	}

	public boolean crudWordValidate() {
		if (crudWord.getText().equals("")) {
			System.out.println("word invalid");
		}
		return !crudWord.getText().equals("");
	}

	public boolean crudMeanValidate() {
		if (crudMean.getText().equals("")) {
			System.out.println(crudMean.getText() + "mean invalid");
		}
		return !crudMean.getText().equals("");
	}

	public boolean crudDscValidate() {
		System.out.println("number of crudeDsc: " + crudDsc.getText().split("\n").length);
		return crudDsc.getText().split("\n").length >= 4;

	}

	public boolean crudProValidate() {
        //crudPro.setText(standardString(crudPro.getText()));
		if (crudPro.getText().equals("")) {
			System.out.println("pronunciation invalid");
		}
		return !crudPro.getText().equals("");
	}

	public boolean crudPartOfSpeechValidate() {
		if (crudPartOfSpeech.getText().equals("")) {
			System.out.println("mean invalid");
		}
		return !crudPartOfSpeech.getText().equals("");
        }
        
        public static String standardString(String s) {
			if (s.equals("")) {return s;}
			s = s.trim().replaceAll("\\s+", " ");
			if (s.equals("")) {return s;}
			return s;
        }
}
